In [23]:
whorunsit = "LiezelMac"

if whorunsit == "LiezelMac":
    home_dir = "/Users/ltamon"
elif whorunsit == "LiezelCluster":
    home_dir = "/project/sahakyanlab/ltamon"
else:
    print("The supplied <whorunsit> option is not created in the script.", quote=F)
    
wk_dir = home_dir + "/SahakyanLab/GenomicContactDynamics/26_PredictingCp"
csv_dir = wk_dir + "/out_makeTable"

In [3]:
import pandas as pd
import re
import numpy as np

def concat_chrcsv(csv_dir, chrs):
    
    features = np.array(df.columns)
    is_chosen = [ bool(re.search(pattern=feat_regex, string=feat)) for feat in features ] 
    df = df[ np.append(label_col, features[is_chosen]) ]
    
    return(df)

def choose_features(df, feat_regex, label_col):
    
    final_regex = feat_regex + '|' + label_col
    is_chosen = [ bool(re.search(pattern=final_regex, string=feat)) for feat in df.columns ] 
    is_todrop = [not bool for bool in is_chosen]
    df.drop(columns=list(df.columns[is_todrop]), inplace=True)

    return(df)
    
def switch_contact(df):
    
    features = np.array(df.columns)
    is_icol = ['.i_' in feat for feat in features]
    is_jcol = ['.j_' in feat for feat in features]
    
    features_switch = np.array(features)
    features_switch[is_icol] = features[is_jcol]
    features_switch[is_jcol] = features[is_icol]
    
    df_switch = df.set_axis(features_switch, axis=1, inplace=False)
    df_switch = df_switch[features]
    df = pd.concat([df, df_switch])
    
    return(df)

In [32]:
gcb = 'min2Mb'
chrs = 'chr21'
csv_path = csv_dir + '/' + gcb + '_' + chr + '_MLtbl.csv'
dflist = [pd.read_csv(csv_path) for chr in chrs]
df = pd.concat(dflist)

NameError: name 'f' is not defined

In [33]:
len(df)

1559855

In [6]:
feat_regex = 'grp.compl.'
df = choose_features(df, feat_regex, 'label')
switch_contact(df)

,label,grp.compl.ij_anvdist,grp.compl.ij_CIIkmer,grp.compl.ij_CIIG,grp.compl.ij_CIIalign
0,6,2234.495310,-1.2627,-0.000020,-0.513900
1,8,2577.978790,-1.2975,-0.000020,-0.520200
2,9,1756.299497,-1.4243,-0.000019,-0.527000
3,4,3603.515907,-1.5271,-0.000020,-0.525350
4,8,4365.757094,-1.4998,-0.000020,-0.527725
...,...,...,...,...,...
311966,10,4795.648879,-1.3605,-0.000023,-0.538475
311967,16,3313.459469,-1.1830,-0.000024,-0.531275
311968,13,4838.429222,-1.4811,-0.000022,-0.533800
311969,13,3636.950564,-1.0367,-0.000025,-0.533725
311970,12,2854.515797,-1.0911,-0.000024,-0.531600